name: ace_thetic
description: An Ecommerce application for an auction.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.5.0
  provider: ^6.0.5
  file_picker: ^10.3.2 # Latest stable version. Desktop warnings can be ignored if not targeting desktop.
  flutter_secure_storage: ^9.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  mime: ^2.0.0
  http_parser: ^4.0.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dashboard_bg.jpg
